import 'package:json_annotation/json_annotation.dart';

part 'chat_message.g.dart'; // File to be generated by build_runner

@JsonSerializable(fieldRename: FieldRename.snake)
class ChatMessage {
  final String id;
  final String role; // 'user' or 'assistant'
  final String content;
  final DateTime timestamp;

  ChatMessage({
    required this.id,
    required this.role,
    required this.content,
    required this.timestamp,
  });

  factory ChatMessage.fromJson(Map<String, dynamic> json) =>
      _$ChatMessageFromJson(json);
  Map<String, dynamic> toJson() => _$ChatMessageToJson(this);

  bool get isUser => role == 'user';
  bool get isAssistant => role == 'assistant';
}
