import 'package:json_annotation/json_annotation.dart';

part 'destination.g.dart'; // File to be generated by build_runner

@JsonSerializable(fieldRename: FieldRename.snake)
class Destination {
  final String id;
  final String name;
  final String? country;
  final String? description;
  final double? budget;
  final List<String> attractions;
  final String? imageUrl;
  final DateTime createdAt;

  Destination({
    required this.id,
    required this.name,
    this.country,
    this.description,
    this.budget,
    required this.attractions,
    this.imageUrl,
    required this.createdAt,
  });

  factory Destination.fromJson(Map<String, dynamic> json) =>
      _$DestinationFromJson(json);
  Map<String, dynamic> toJson() => _$DestinationToJson(this);

  String get displayName => country != null ? '$name, $country' : name;
}
