name: wanderai
description: AI-powered travel planning mobile app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.0
  riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

  # Navigation
  go_router: ^14.6.2

  # HTTP & Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  firebase_ai: ^2.3.0
  google_sign_in: ^7.2.0

  # Local Storage
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.3
  google_fonts: ^6.3.2
  fl_chart: ^1.1.1

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  url_launcher: ^6.3.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^3.0.0
  json_serializable: ^6.8.0

  # Riverpod Linting
  riverpod_lint: ^3.0.0
  custom_lint: ^0.8.0

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design:
    true

    # Add assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # Add fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
