// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIU_HJNmvUvUEyt473kPvAMnrf-H_KDdo',
    appId: '1:605323428281:android:37cc70e56e51bf141eb668',
    messagingSenderId: '605323428281',
    projectId: 'wanderai-e2eef',
    storageBucket: 'wanderai-e2eef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYD7daHu96W9y9Bf3RwoO_DwM71s4U1Eg',
    appId: '1:605323428281:ios:4f7347555d935bf01eb668',
    messagingSenderId: '605323428281',
    projectId: 'wanderai-e2eef',
    storageBucket: 'wanderai-e2eef.firebasestorage.app',
    androidClientId: '605323428281-6228vl3bq1r9nib841itaj1o44lmek9t.apps.googleusercontent.com',
    iosClientId: '605323428281-ce0s0f9f015oqn8i8d49furjtra1ljci.apps.googleusercontent.com',
    iosBundleId: 'com.example.wanderai',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC31iFBQd-iIXdgkfm-sCZeNx3UZcIyFvc',
    appId: '1:605323428281:web:82d0bc3a4288183c1eb668',
    messagingSenderId: '605323428281',
    projectId: 'wanderai-e2eef',
    authDomain: 'wanderai-e2eef.firebaseapp.com',
    storageBucket: 'wanderai-e2eef.firebasestorage.app',
    measurementId: 'G-XW4TDVXWEG',
  );

}