name: Flutter Analysis & Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "mobile/**"
      - ".github/workflows/flutter-tests.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "mobile/**"

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
          channel: "stable"

      - name: Get Flutter dependencies
        working-directory: ./mobile
        run: flutter pub get

      - name: Analyze project
        working-directory: ./mobile
        run: flutter analyze

      - name: Run tests
        working-directory: ./mobile
        run: flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./mobile/coverage/lcov.info
          flags: mobile
          name: mobile-coverage
